### ISSUE TITLE
Device configuration

### ISSUE THREAD

**Issue by Matteo04052017** [ska-telescope/tmc-prototype#24]
At the moment the configuration of the containers of this repository happen in 2 steps: the first one configure the database (addDevicesAndProperties.py) and the second one configure polling and event (configurePollingAndEvents.py).

The second script has to wait all the devices to be up and running to be executed and this create a problem because it is not possible to be sure of the time to wait (if, for instance, one of the dish leaf node has a problem, this script will never execute). 

I think that the best option would be to create a configuration file for each device (that could be extended more easily) and load them in the init command of each device, removing from the "devices.json" file all the information that are not going into the database (like pollingPeriod or changeEventAbs). 

Please let me know if you have any doubts.

**Comment by jyotinpo** [comment]
Hi @Matteo04052017 ,
I assume that since the `tmc-prototype` has started using [dsconfig](https://github.com/MaxIV-KitsControls/lib-maxiv-dsconfig) tool, the concern behind the device configuration is addressed to some extent. Do you still foresee a need to have a configuration file per device? If required we can discuss this as a topic in any of the upcoming TANGO CoP meetings.
Are we good to close this issue?

**Comment by Matteo04052017** [comment]
No, I don't foresee the need to have a configuration file per device.
